### ISSUE TITLE
The testing link in the README is a 404

### ISSUE THREAD

**Issue by andersfylling** [blurplejs/testing#1]

**Comment by padarom** [comment]
Will fix in a minute, the link at the top of the repo is the correct one. There's not actually any information on the documentation yet however, just a placeholder text. I'll try to get some more information about what I envision the eventual API to be on there tomorrow.

**Comment by padarom** [comment]
https://blurple.js.org/testing/ has some things written down now. It's still missing content regarding faking events, but it should bring the gist of what it is going to be across now.
